/* ─────────────────────────────────────────────────────────────
   MARKETING AI WORKFLOW CONSOLE — app.js
   Universal AI provider layer: Claude · OpenAI · Custom endpoint
   Falls back to simulation mode when no key is configured.
───────────────────────────────────────────────────────────── */

/* ── DOM REFERENCES ──────────────────────────────────────── */

const fields = {
  company:       document.querySelector("#company"),
  contact:       document.querySelector("#contact"),
  industry:      document.querySelector("#industry"),
  goal:          document.querySelector("#goal"),
  brandVoice:    document.querySelector("#brandVoice"),
  offer:         document.querySelector("#offer"),
  humanReview:   document.querySelector("#humanReview"),
  sourceCitations: document.querySelector("#sourceCitations"),
  createTask:    document.querySelector("#createTask"),
  creativeBrief: document.querySelector("#creativeBrief"),
  aiProvider:    document.querySelector("#aiProvider"),
  aiModel:       document.querySelector("#aiModel"),
  apiKey:        document.querySelector("#apiKey"),
  customEndpoint: document.querySelector("#customEndpoint"),
};

const output = {
  fitScore:          document.querySelector("#fitScore"),
  qualificationList: document.querySelector("#qualificationList"),
  emailDraft:        document.querySelector("#emailDraft"),
  briefDraft:        document.querySelector("#briefDraft"),
  taskBoard:         document.querySelector("#taskBoard"),
  auditLog:          document.querySelector("#auditLog"),
};

const ui = {
  statusDot:          document.querySelector("#statusDot"),
  statusTitle:        document.querySelector("#statusTitle"),
  statusSub:          document.querySelector("#statusSub"),
  statusPanel:        document.querySelector("#statusPanel"),
  providerNote:       document.querySelector("#providerNote"),
  customEndpointLabel: document.querySelector("#customEndpointLabel"),
  toggleKey:          document.querySelector("#toggleKey"),
  runBtn:             document.querySelector("#runWorkflow"),
  classifierTag:      document.querySelector("#classifierTag"),
  copyEmail:          document.querySelector("#copyEmail"),
  copyBrief:          document.querySelector("#copyBrief"),
};

/* ── PROVIDER MODEL CATALOGUE ────────────────────────────── */

const MODEL_OPTIONS = {
  claude: [
    { value: "claude-fable-5", label: "Claude Fable 5" },
    { value: "claude-mythos-5", label: "Claude Mythos 5" },
    { value: "claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
    { value: "claude-opus-4-8",   label: "Claude Opus (recommended) 4.8" },
    { value: "claude-haiku-4-5-20251001", label: "Claude Haiku 4.5" },
  ],
  openai: [
    { value: "gpt-5.5", label: "GPT-5.5" },
    { value: "gpt-5.4", label: "GPT-5.4" },
    { value: "gpt-5.4-mini", label: "GPT-5.4 mini (recommended)" },
    { value: "gpt-5.4-nano", label: "GPT-5.4 nano" },
  ],
  openrouter: [
    { value: "openrouter/free", label: "Openrouter Free Model" },
  ],
  custom: [
    { value: "default", label: "Default model (set by your endpoint)" },
  ],
  simulation: [
    { value: "sim", label: "Simulation engine" },
  ],
};

const PROVIDER_NOTES = {
  simulation: "Running in simulation mode. Outputs are generated by deterministic local logic — no API key required. Useful for testing the workflow structure without consuming API credits.",
  claude:     "Claude (Anthropic) — send requests to api.anthropic.com. Your API key is used only for direct requests to Anthropic and is never stored or logged by this app.",
  openai:     "OpenAI — send requests to api.openai.com. Your API key is used only for direct requests to OpenAI and is never stored or logged by this app.",
  openrouter: "OpenRouter — send requests to api.openrouter.ai. Your API key is used only for direct requests to OpenRouter and is never stored or logged by this app.",
  custom:     "Custom / in-house endpoint — sends OpenAI-compatible POST requests to the URL you specify. Most enterprise AI gateways accept this format. If your endpoint uses a different schema, you may need to adjust the request structure in app.js.",
};

/* ── SAMPLE DATA ─────────────────────────────────────────── */

const sampleLead = {
  company:  "Northstar Dental Group",
  contact:  "Maya Chen",
  industry: "Healthcare",
  goal:     "We run three dental clinics and want more high-intent appointment requests from Google Ads. Our current landing page gets traffic, but the conversion rate feels low and the team does not know which campaigns are wasting spend.",
};

const industrySignals = {
  Healthcare:    ["local intent", "trust signals", "appointment conversion", "review management"],
  SaaS:          ["pipeline quality", "trial activation", "sales enablement", "retention messaging"],
  "Real estate": ["lead quality", "local SEO", "listing creative", "agent follow-up"],
  Education:     ["enrollment funnel", "parent/student concerns", "open house conversion", "program differentiation"],
  Retail:        ["offer testing", "creative velocity", "seasonal campaigns", "repeat purchase"],
};

/* ── UTILITY ─────────────────────────────────────────────── */

function nowLabel() {
  return new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" });
}

function providerBadgeHtml() {
  const p = fields.aiProvider.value;
  const labels = { claude: "Claude", openai: "OpenAI", openrouter: "OpenRouter", custom: "Custom API", simulation: "Sim" };
  const classes = { claude: "badge-claude", openai: "badge-openai", openrouter: "badge-openrouter", custom: "badge-custom", simulation: "badge-sim" };
  return `<span class="provider-badge ${classes[p] || 'badge-sim'}">${labels[p] || p}</span>`;
}

function log(message) {
  const row = document.createElement("div");
  row.className = "audit-row";
  row.innerHTML = `<time>${nowLabel()}${providerBadgeHtml()}</time><span>${message}</span>`;
  output.auditLog.prepend(row);
}

function getLead() {
  return {
    company:    fields.company.value.trim(),
    contact:    fields.contact.value.trim(),
    industry:   fields.industry.value,
    goal:       fields.goal.value.trim(),
    brandVoice: fields.brandVoice.value.trim(),
    offer:      fields.offer.value.trim(),
  };
}

function validateLead(lead) {
  const missing = [];
  if (!lead.company) missing.push("company");
  if (!lead.contact) missing.push("contact name");
  if (!lead.goal)    missing.push("goal");
  return missing;
}

function setRunLoading(isLoading) {
  ui.runBtn.disabled = isLoading;
  ui.runBtn.textContent = isLoading ? "Running…" : "Run workflow";
  if (isLoading) {
    ui.runBtn.classList.add("loading-btn");
    ui.statusDot.classList.add("loading");
  } else {
    ui.runBtn.classList.remove("loading-btn");
    ui.statusDot.classList.remove("loading");
  }
}

/* ── UNIVERSAL AI CALLER ─────────────────────────────────── */
/*
  callAI(prompt) → Promise<string>

  Normalises the request/response for each provider so the
  rest of the app never needs to know which API is running.

  Provider     Endpoint                                      Auth header
  ──────────── ───────────────────────────────────────────── ────────────────────
  claude       https://api.anthropic.com/v1/messages         x-api-key + anthropic-version
  openai       https://api.openai.com/v1/chat/completions    Authorization: Bearer
  openrouter    https://api.openrouter.ai/v1/chat/completions Authorization: Bearer
  custom       <user-supplied base URL>/chat/completions     Authorization: Bearer
  simulation   (local JS — no fetch)                        —
*/

async function callAI(prompt) {
  const provider = fields.aiProvider.value;
  const model    = fields.aiModel.value;
  const apiKey   = fields.apiKey.value.trim();

  if (provider === "simulation") {
    return null; // signal to caller: use local fallback
  }

  if (!apiKey) {
    throw new Error("API key is required. Enter your key in Step 0.");
  }

  let url, headers, body;

  if (provider === "claude") {
    url = "https://api.anthropic.com/v1/messages";
    headers = {
      "Content-Type":      "application/json",
      "x-api-key":         apiKey,
      "anthropic-version": "2023-06-01",
      "anthropic-dangerous-direct-browser-access": "true",
    };
    body = JSON.stringify({
      model,
      max_tokens: 1024,
      messages: [{ role: "user", content: prompt }],
    });

  } else if (provider === "openai") {
    url = "https://api.openai.com/v1/chat/completions";
    headers = {
      "Content-Type":  "application/json",
      "Authorization": `Bearer ${apiKey}`,
    };
    body = JSON.stringify({
      model,
      max_tokens: 1024,
      messages: [{ role: "user", content: prompt }],
    });

      } else if (provider === "openrouter") {
    url = "https://openrouter.ai/api/v1/messages";
    headers = {
      "Content-Type":  "application/json",
      "Authorization": `Bearer ${apiKey}`,
    };
    body = JSON.stringify({
      model,
      max_tokens: 1024,
      messages: [{ role: "user", content: prompt }],
    });

  } else if (provider === "custom") {
    const base = fields.customEndpoint.value.trim().replace(/\/$/, "");
    if (!base) throw new Error("Enter your custom endpoint URL in Step 0.");
    url = `${base}/chat/completions`;
    headers = {
      "Content-Type":  "application/json",
      "Authorization": `Bearer ${apiKey}`,
    };
    body = JSON.stringify({
      model: model === "default" ? undefined : model,
      max_tokens: 1024,
      messages: [{ role: "user", content: prompt }],
    });

  }

  const response = await fetch(url, { method: "POST", headers, body });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    const msg = err?.error?.message || err?.message || response.statusText;
    throw new Error(`${provider} API error (${response.status}): ${msg}`);
  }

  const data = await response.json();

  // Normalise response to plain string regardless of provider
  if (provider === "claude") {
    return data?.content?.[0]?.text ?? "";
  } else {
    // OpenAI-compatible shape (openai + openrouter + custom)
    return data?.choices?.[0]?.message?.content ?? "";
  }
}

/* ── AI-POWERED QUALIFICATION ────────────────────────────── */

async function classifyLeadAI(lead) {
  const prompt = `You are a senior marketing strategist qualifying inbound leads.

Lead details:
- Company: ${lead.company}
- Industry: ${lead.industry}
- Goal: ${lead.goal}
- Brand voice on file: ${lead.brandVoice}
- Approved offer: ${lead.offer}

Respond with ONLY valid JSON in this exact format (no explanation, no markdown):
{
  "score": <integer 0-96>,
  "urgency": "<High|Medium|Low>",
  "fit": "<one sentence: fit assessment>",
  "nextAction": "<one sentence: recommended next step>",
  "risk": "<one sentence: risk or governance note>"
}`;

  const raw = await callAI(prompt);
  if (!raw) return null; // simulation fallback

  try {
    const clean = raw.replace(/```json|```/g, "").trim();
    return JSON.parse(clean);
  } catch {
    throw new Error("Could not parse qualification response from AI. Raw response logged to console.");
  }
}

/* ── SIMULATION FALLBACK (original deterministic logic) ──── */

function classifyLeadSim(lead) {
  const goal = lead.goal.toLowerCase();
  let score = 52;
  if (goal.includes("conversion") || goal.includes("appointments") || goal.includes("leads")) score += 16;
  if (goal.includes("google ads") || goal.includes("paid") || goal.includes("campaign")) score += 12;
  if (goal.includes("wasting spend") || goal.includes("low") || goal.includes("urgent")) score += 10;
  if (lead.brandVoice.length > 40 && lead.offer.length > 40) score += 6;
  score = Math.min(score, 96);

  return {
    score,
    urgency:    score >= 82 ? "High" : score >= 68 ? "Medium" : "Low",
    fit:        score >= 80 ? "Strong fit" : score >= 65 ? "Qualified but needs discovery" : "Needs manual review",
    risk:       fields.humanReview.checked
                  ? "Controlled: external email remains draft until approval."
                  : "High: sending without review is not recommended in practice mode.",
    nextAction: score >= 75
                  ? "Book a diagnostic call and request current campaign metrics."
                  : "Ask clarifying questions before proposing a sprint.",
  };
}

/* ── RENDER QUALIFICATION ────────────────────────────────── */

function renderQualification(analysis) {
  output.fitScore.textContent = analysis.score;
  output.qualificationList.innerHTML = "";
  [
    ["Fit",         analysis.fit],
    ["Urgency",     analysis.urgency],
    ["Next action", analysis.nextAction],
    ["Risk note",   analysis.risk],
  ].forEach(([label, value]) => {
    const item = document.createElement("div");
    item.className = "metric";
    item.innerHTML = `<strong>${label}</strong><span>${value}</span>`;
    output.qualificationList.appendChild(item);
  });
}

/* ── EMAIL DRAFT ─────────────────────────────────────────── */

async function buildEmailDraft(lead, analysis) {
  const sourceNote = fields.sourceCitations.checked
    ? "\n\nSource notes: Lead intake form, approved offer text, and project brand voice were used. No external facts were added."
    : "";
  const approvalNote = fields.humanReview.checked
    ? "\n\nStatus: DRAFT FOR HUMAN REVIEW. Do not send until the account owner checks fit, claims, and next-step accuracy."
    : "\n\nStatus: REVIEW WARNING. This tool recommends approval before sending.";

  const aiResult = await callAI(
    `You are a business development writer. Write a concise, professional outreach email using the details below.
Return ONLY the email text — no subject line prefix, no explanation, no markdown.

Company: ${lead.company}
Contact name: ${lead.contact}
Industry: ${lead.industry}
Their goal: ${lead.goal}
Our approved offer: ${lead.offer}
Brand voice to match: ${lead.brandVoice}
Qualification summary: ${analysis.fit}; urgency: ${analysis.urgency}; recommended next step: ${analysis.nextAction}

Format: Subject line on first line, blank line, then email body. End with "Best,\nMarketing team".`
  );

  if (aiResult) {
    return aiResult + sourceNote + approvalNote;
  }

  // Simulation fallback
  return `Subject: Next step for ${lead.company}'s growth diagnostic

Hi ${lead.contact},

Thank you for sharing the context around ${lead.company}'s ${lead.industry.toLowerCase()} marketing goals. Based on your note, the highest-value starting point appears to be a focused diagnostic of campaign spend, landing-page conversion, and lead quality.

Recommended next step:
Schedule a 30-minute discovery call so we can review the current funnel, identify where performance is leaking, and decide whether a 30-day campaign sprint is appropriate.

Why this makes sense:
- Your stated goal indicates a measurable acquisition problem.
- The approved offer matches the need: ${lead.offer}
- Initial qualification: ${analysis.fit}; urgency: ${analysis.urgency}.

Best,
Marketing team${sourceNote}${approvalNote}`;
}

/* ── CREATIVE BRIEF ──────────────────────────────────────── */

async function buildCreativeBrief(lead, analysis) {
  if (!fields.creativeBrief.checked) return "Creative brief creation is turned off.";

  const signals = industrySignals[lead.industry] || [];

  const aiResult = await callAI(
    `You are a creative director briefing a design team. Write a creative brief for the campaign below.
Return ONLY the brief text — no explanation, no markdown headers with ##.

Company: ${lead.company}
Industry: ${lead.industry}
Goal: ${lead.goal}
Brand voice: ${lead.brandVoice}
Industry signals relevant to this campaign: ${signals.join(", ")}
Qualification: ${analysis.fit}; urgency: ${analysis.urgency}

The brief should cover: Objective, Audience, Message angle, Tone, and a Required human review note.`
  );

  if (aiResult) return aiResult;

  // Simulation fallback
  return `Creative brief: ${lead.company} diagnostic campaign

Objective:
Create one landing-page hero concept and three ad creative directions for a ${lead.industry.toLowerCase()} lead-generation diagnostic.

Audience:
Decision-maker researching marketing improvement, campaign efficiency, or conversion growth.

Message angle:
Reduce wasted spend, clarify funnel performance, and turn campaign traffic into qualified opportunities.

Useful industry signals:
- ${signals.join("\n- ")}

Tone:
${lead.brandVoice}

Required human review:
Confirm claims, compliance constraints, brand accuracy, and whether before/after language is permitted.`;
}

/* ── TASK RENDERING (unchanged) ─────────────────────────── */

function renderTask(lead, analysis) {
  if (!fields.createTask.checked) {
    output.taskBoard.innerHTML = "<p>Task creation is turned off.</p>";
    return;
  }
  output.taskBoard.innerHTML = `
    <div class="task-card">
      <strong>Follow up with ${lead.company}</strong>
      <div class="task-meta">Owner: Account manager | Status: Needs review | Priority: ${analysis.urgency}</div>
      <p>${analysis.nextAction}</p>
    </div>
    <div class="task-card">
      <strong>Request source materials</strong>
      <div class="task-meta">System: Notion-style task | Due: Next business day</div>
      <p>Ask for campaign export, landing page URL, conversion goal, and last 30 days of lead-quality notes.</p>
    </div>`;
}

/* ── MAIN WORKFLOW ───────────────────────────────────────── */

async function runWorkflow() {
  const lead = getLead();
  const missing = validateLead(lead);
  if (missing.length) {
    log(`<span class="risk">Blocked:</span> missing ${missing.join(", ")}.`);
    return;
  }

  const provider = fields.aiProvider.value;
  const isLive   = provider !== "simulation";

  setRunLoading(true);
  output.emailDraft.classList.add("generating");
  output.briefDraft.classList.add("generating");
  output.emailDraft.textContent = isLive ? "Generating with AI…" : "Running simulation…";
  output.briefDraft.textContent = isLive ? "Generating with AI…" : "Running simulation…";

  try {
    log("Lead intake captured from Gmail/Form simulation.");
    log("Project knowledge retrieved from Google Drive simulation.");

    // Step 2 — Qualification
    let analysis;
    if (isLive) {
      log("Sending qualification request to AI provider…");
      const aiAnalysis = await classifyLeadAI(lead);
      if (aiAnalysis) {
        // Merge governance fields that are local
        analysis = {
          ...aiAnalysis,
          risk: fields.humanReview.checked
            ? aiAnalysis.risk + " Human approval gate is active."
            : aiAnalysis.risk + " Warning: approval gate is disabled.",
        };
        log(`AI provider returned fit score ${analysis.score} — urgency: ${analysis.urgency}.`);
      } else {
        analysis = classifyLeadSim(lead);
        log("Simulation engine assigned fit score (AI path returned empty).");
      }
    } else {
      analysis = classifyLeadSim(lead);
      log(`Simulation engine assigned fit score ${analysis.score} and ${analysis.urgency.toLowerCase()} urgency.`);
    }
    renderQualification(analysis);

    // Step 5 — Email draft
    const email = await buildEmailDraft(lead, analysis);
    output.emailDraft.textContent = email;
    output.emailDraft.classList.remove("generating");
    log(isLive ? "Email draft generated by AI provider." : "Email draft generated by simulation engine.");

    // Step 6 — Creative brief
    const brief = await buildCreativeBrief(lead, analysis);
    output.briefDraft.textContent = brief;
    output.briefDraft.classList.remove("generating");
    if (fields.creativeBrief.checked) {
      log(isLive ? "Creative brief generated by AI provider." : "Simulation creative brief generated.");
    }

    // Step 7 — Tasks
    renderTask(lead, analysis);
    if (fields.createTask.checked) log("Notion-style follow-up tasks created.");

    // Governance gate
    if (fields.humanReview.checked) {
      log("Human approval gate active — external email remains draft until reviewed.");
    } else {
      log(`<span class="warning">Warning:</span> approval gate is disabled for this run.`);
    }

  } catch (err) {
    output.emailDraft.textContent = `Error: ${err.message}`;
    output.emailDraft.classList.remove("generating");
    output.briefDraft.textContent = "Workflow stopped due to error. See audit log.";
    output.briefDraft.classList.remove("generating");
    log(`<span class="risk">Error:</span> ${err.message}`);
    console.error(err);
  } finally {
    setRunLoading(false);
  }
}

/* ── LOAD SAMPLE (unchanged) ─────────────────────────────── */

function loadSample() {
  fields.company.value  = sampleLead.company;
  fields.contact.value  = sampleLead.contact;
  fields.industry.value = sampleLead.industry;
  fields.goal.value     = sampleLead.goal;
  log("Sample lead loaded.");
}

/* ── RESET (unchanged) ───────────────────────────────────── */

function resetWorkflow() {
  fields.company.value  = "";
  fields.contact.value  = "";
  fields.industry.value = "Healthcare";
  fields.goal.value     = "";
  output.fitScore.textContent        = "--";
  output.qualificationList.innerHTML = "<p>Run the workflow to classify urgency, fit, next action, and risk notes.</p>";
  output.emailDraft.textContent      = "Run the workflow to generate a client-safe draft.";
  output.briefDraft.textContent      = "Run the workflow to generate a design brief.";
  output.taskBoard.innerHTML         = "<p>No task created yet.</p>";
  output.auditLog.innerHTML          = "";
  log("Workflow reset.");
}

/* ── PROVIDER UI LOGIC ───────────────────────────────────── */

function updateProviderUI() {
  const p = fields.aiProvider.value;

  // Model dropdown
  const models = MODEL_OPTIONS[p] || [];
  fields.aiModel.innerHTML = models.map(m =>
    `<option value="${m.value}">${m.label}</option>`
  ).join("");

  // Custom endpoint visibility
  ui.customEndpointLabel.style.display = p === "custom" ? "grid" : "none";

  // Provider note
  ui.providerNote.textContent  = PROVIDER_NOTES[p] || "";
  ui.providerNote.className    = "provider-note";

  // Status panel
  const isLive = p !== "simulation";
  const hasKey = fields.apiKey.value.trim().length > 0;
  const ready  = !isLive || hasKey;

  ui.statusDot.className = ready && isLive ? "status-dot active" : "status-dot";
  ui.statusPanel.className = ready && isLive ? "status-panel connected" : "status-panel";

  const providerLabels = { claude: "Claude (Anthropic)", openai: "OpenAI", openrouter: "OpenRouter", custom: "Custom endpoint", simulation: "Simulation mode" };
  ui.statusTitle.textContent = providerLabels[p] || p;
  ui.statusSub.textContent   = isLive
    ? (hasKey ? "API key configured — ready to run." : "Enter your API key above to enable AI generation.")
    : "Running local simulation — no API key required.";

  // AI tag badges on output panels
  document.querySelectorAll(".ai-tag").forEach(el => {
    el.classList.toggle("live", isLive && hasKey);
  });
}

/* ── COPY BUTTONS ────────────────────────────────────────── */

function setupCopy(btnId, sourceId) {
  const btn = document.querySelector(`#${btnId}`);
  const src = document.querySelector(`#${sourceId}`);
  if (!btn || !src) return;
  btn.addEventListener("click", () => {
    const text = src.textContent;
    navigator.clipboard.writeText(text).catch(() => {
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      ta.remove();
    });
    btn.textContent = "Copied!";
    btn.classList.add("copied");
    setTimeout(() => {
      btn.textContent = "Copy";
      btn.classList.remove("copied");
    }, 2000);
  });
}

/* ── API KEY TOGGLE ──────────────────────────────────────── */

ui.toggleKey.addEventListener("click", () => {
  const isHidden = fields.apiKey.type === "password";
  fields.apiKey.type = isHidden ? "text" : "password";
  ui.toggleKey.textContent = isHidden ? "Hide" : "···";
});

/* ── EVENT LISTENERS ─────────────────────────────────────── */

document.querySelector("#loadSample").addEventListener("click", loadSample);
document.querySelector("#runWorkflow").addEventListener("click", runWorkflow);
document.querySelector("#resetWorkflow").addEventListener("click", resetWorkflow);

fields.aiProvider.addEventListener("change", updateProviderUI);
fields.apiKey.addEventListener("input", updateProviderUI);

setupCopy("copyEmail", "emailDraft");
setupCopy("copyBrief", "briefDraft");

/* ── INIT ────────────────────────────────────────────────── */

updateProviderUI();
log("Console initialised.");
